on: [push, pull_request]
name: Integracion continua con node.js
jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone and checkout'
        uses: actions/checkout@v1
      - name: 'use node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: 'install dependencies'
        run: npm ci
      - name: 'run eslint'
        run: npm run lint
      - name: 'npm run tests'
        run: npm test
