on: [push, pull_request]
name: Integracion continua con node.js
jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: 'clone and checkout'
        uses: actions/checkout@v1
      - name: 'use node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: 'install dependencies'
        run: npm ci
      - name: 'run eslint'
        run: npm run lint
      - name: 'npm run tests'
        run: npm test
  #cd:
  #  runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Docker login
  #       run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
  #    - name: Build
  #       run: docker build -t back
  #    - name: Tags
  #       run: |
  #         docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
  #         docker tag back ${{ secrets.DOCKER_USER }}/back:latest
  #    - name: Push
  #       run: |
  #         docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
  #         docker push ${{ secrets.DOCKER_USER }}/back:latest
